import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

type Documents = {
    "query ConsultarIndiceNombres {\n  allPeople {\n    totalCount\n    people {\n      id\n      name\n    }\n  }\n}": typeof types.ConsultarIndiceNombresDocument,
    "query ConsultarPeliculas {\n  allFilms {\n    totalCount\n    films {\n      id\n      title\n      episodeID\n      director\n      releaseDate\n      planetConnection {\n        totalCount\n        planets {\n          id\n          name\n        }\n      }\n      characterConnection {\n        totalCount\n        characters {\n          id\n          name\n        }\n      }\n    }\n  }\n}": typeof types.ConsultarPeliculasDocument,
    "query ConsultarPersonaje($id: ID!) {\n  person(id: $id) {\n    id\n    name\n    gender\n    birthYear\n    height\n    mass\n    eyeColor\n    hairColor\n    skinColor\n    homeworld {\n      id\n      name\n    }\n    species {\n      id\n      name\n    }\n    starshipConnection {\n      totalCount\n      starships {\n        id\n        name\n      }\n    }\n    filmConnection {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      films {\n        id\n        title\n        episodeID\n        director\n        releaseDate\n        planetConnection {\n          totalCount\n          planets {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n}": typeof types.ConsultarPersonajeDocument,
    "query ConsultarPersonajes($first: Int!, $after: String) {\n  allPeople(first: $first, after: $after) {\n    totalCount\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n    people {\n      id\n      name\n      gender\n      birthYear\n    }\n  }\n}": typeof types.ConsultarPersonajesDocument,
};
const documents: Documents = {
    "query ConsultarIndiceNombres {\n  allPeople {\n    totalCount\n    people {\n      id\n      name\n    }\n  }\n}": types.ConsultarIndiceNombresDocument,
    "query ConsultarPeliculas {\n  allFilms {\n    totalCount\n    films {\n      id\n      title\n      episodeID\n      director\n      releaseDate\n      planetConnection {\n        totalCount\n        planets {\n          id\n          name\n        }\n      }\n      characterConnection {\n        totalCount\n        characters {\n          id\n          name\n        }\n      }\n    }\n  }\n}": types.ConsultarPeliculasDocument,
    "query ConsultarPersonaje($id: ID!) {\n  person(id: $id) {\n    id\n    name\n    gender\n    birthYear\n    height\n    mass\n    eyeColor\n    hairColor\n    skinColor\n    homeworld {\n      id\n      name\n    }\n    species {\n      id\n      name\n    }\n    starshipConnection {\n      totalCount\n      starships {\n        id\n        name\n      }\n    }\n    filmConnection {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      films {\n        id\n        title\n        episodeID\n        director\n        releaseDate\n        planetConnection {\n          totalCount\n          planets {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n}": types.ConsultarPersonajeDocument,
    "query ConsultarPersonajes($first: Int!, $after: String) {\n  allPeople(first: $first, after: $after) {\n    totalCount\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n    people {\n      id\n      name\n      gender\n      birthYear\n    }\n  }\n}": types.ConsultarPersonajesDocument,
};

export function graphql(source: string): unknown;

export function graphql(source: "query ConsultarIndiceNombres {\n  allPeople {\n    totalCount\n    people {\n      id\n      name\n    }\n  }\n}"): (typeof documents)["query ConsultarIndiceNombres {\n  allPeople {\n    totalCount\n    people {\n      id\n      name\n    }\n  }\n}"];
export function graphql(source: "query ConsultarPeliculas {\n  allFilms {\n    totalCount\n    films {\n      id\n      title\n      episodeID\n      director\n      releaseDate\n      planetConnection {\n        totalCount\n        planets {\n          id\n          name\n        }\n      }\n      characterConnection {\n        totalCount\n        characters {\n          id\n          name\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query ConsultarPeliculas {\n  allFilms {\n    totalCount\n    films {\n      id\n      title\n      episodeID\n      director\n      releaseDate\n      planetConnection {\n        totalCount\n        planets {\n          id\n          name\n        }\n      }\n      characterConnection {\n        totalCount\n        characters {\n          id\n          name\n        }\n      }\n    }\n  }\n}"];
export function graphql(source: "query ConsultarPersonaje($id: ID!) {\n  person(id: $id) {\n    id\n    name\n    gender\n    birthYear\n    height\n    mass\n    eyeColor\n    hairColor\n    skinColor\n    homeworld {\n      id\n      name\n    }\n    species {\n      id\n      name\n    }\n    starshipConnection {\n      totalCount\n      starships {\n        id\n        name\n      }\n    }\n    filmConnection {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      films {\n        id\n        title\n        episodeID\n        director\n        releaseDate\n        planetConnection {\n          totalCount\n          planets {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query ConsultarPersonaje($id: ID!) {\n  person(id: $id) {\n    id\n    name\n    gender\n    birthYear\n    height\n    mass\n    eyeColor\n    hairColor\n    skinColor\n    homeworld {\n      id\n      name\n    }\n    species {\n      id\n      name\n    }\n    starshipConnection {\n      totalCount\n      starships {\n        id\n        name\n      }\n    }\n    filmConnection {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      films {\n        id\n        title\n        episodeID\n        director\n        releaseDate\n        planetConnection {\n          totalCount\n          planets {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n}"];
export function graphql(source: "query ConsultarPersonajes($first: Int!, $after: String) {\n  allPeople(first: $first, after: $after) {\n    totalCount\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n    people {\n      id\n      name\n      gender\n      birthYear\n    }\n  }\n}"): (typeof documents)["query ConsultarPersonajes($first: Int!, $after: String) {\n  allPeople(first: $first, after: $after) {\n    totalCount\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n    people {\n      id\n      name\n      gender\n      birthYear\n    }\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;
